### ISSUE TITLE
Add bottles for older versions of macOS

### ISSUE THREAD

**Issue by fniephaus** [akeru-inc/xcnotary#5]
Travis CI (and other CI providers) support many different versions of macOS (see [here](https://docs.travis-ci.com/user/reference/osx/#jdk-and-macos)). On non-Catalina systems, xcnotary is built from scratch. This, however, can take [more than 7mins](https://travis-ci.org/github/squeak-smalltalk/squeak-app/jobs/683725283#L8782), which is a long time for CI builds. It'd be great if bottles for older versions of macOS could be provided.

Many thanks,
Fabio

**Comment by fniephaus** [comment]
In the meantime, `brew install --force-bottle akeru-inc/tap/xcnotary` can be used as a workaround.

**Comment by davidvartan** [comment]
Thank you for the comment!

Would you be able to share the reason for not using Catalina to build? Would be helpful to gauge if a lot of people are doing this. FWIW, you can still target older OS X versions even if building with latest OS X. 

- 10.14.5 with Xcode 11 would be the oldest that could be supported due to e.g. the use of `xcrun altool`.

- Def. please let me know if the tool works well for you on Mojave (I unfortunately don't have a test box on hand). While the tool will launch, my concern is with tool dependencies, namely `altool`, `spctl`, `codesign` and any quirks in their behavior between OS X versions.

I would probably keep this issue open to gather more feedback. Would be most meaningful to standarize on the latest OS X/toolchain for everyone to have a consistent experience. In the ideal case, Apple would have provided a web-based API to submit builds/etc., so that the process could be completely platform-agnostic, but unfortunately it isn't the case at the moment.

**Comment by fniephaus** [comment]
Hi David,
First of all, thanks for your work on xcnotary! And thanks for the response.

Good to know that xcnotary requires Xcode 11 and later.

We can't use Catalina at the moment, because we also still target macOS 32bit. It makes sense to collect more feedback before starting to add support. I'll try to see if we can upgrade to Xcode 11 and use `--force-bottle` to install the Catalina bottle on Mojave in the meantime.

**Comment by davidvartan** [comment]
Hi @fniephaus, wanted to see if you've had a chance to try xcnotary with `--force-bottle` on your Mojave machine. Thank you!

**Comment by fniephaus** [comment]
Hi @davidvartan, yes...seems to work. [Here's an example](https://travis-ci.org/github/squeak-smalltalk/squeak-app/jobs/690358602#L4373).

**Comment by davidvartan** [comment]
That's great, it confirms what I was hoping since the tool itself a self-contained binary other than dependency on Xcode stuff. Going to mark the bottle as compatible with both versions for convenience. Thank you for confirming!

**Comment by davidvartan** [comment]
This should be working now without `--force-bottle`. Give it a try please and let me know. (`brew update && brew upgrade  akeru-inc/tap/xcnotary` if you're doing it locally.)

**Comment by fniephaus** [comment]
Seems to be working now, thanks!
